
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-15
owner: ucsb-cs156-f24
repo_name: team01-f24-15
pull_requests: [{"author":{"id":"U_kgDOBkByCg","is_bot":false,"login":"Nopesy","name":"Cooper Hawley"},"headRefName":"DiningCommonsMenuItem-Controller","number":53,"title":"Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/53"},{"author":{"id":"MDQ6VXNlcjY0MzQwNDE3","is_bot":false,"login":"ranjanbhavya","name":""},"headRefName":"Bhavya-MenuItemReviews","number":52,"title":" Created MenuItemReview controller, added get/post endpoints, and added get (show)","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/52"}]
