
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-15
owner: ucsb-cs156-f24
repo_name: team01-f24-15
pull_requests: [{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-Add-Delete","number":59,"title":"Added DELETE endpoint for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/59"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-Add-Put","number":58,"title":"Added PUT (edit) endpoint for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/58"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-Articles-Add-Get","number":57,"title":"Added GET (show) endpoint for Articles","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/57"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-ArticlesController","number":56,"title":"Created Article Controller and Tests, Added Get (index) and Post (create)","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/56"},{"author":{"id":"MDQ6VXNlcjY0MzQwNDE3","is_bot":false,"login":"ranjanbhavya","name":""},"headRefName":"Bhavya-MenuItemReviews","number":55,"title":"Added put and delete endpoint","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/55"},{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophia-RecRequestTable","number":54,"title":"adding PUT(edit) to my recommendation request controller + test","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/54"},{"author":{"id":"U_kgDOBkByCg","is_bot":false,"login":"Nopesy","name":"Cooper Hawley"},"headRefName":"DiningCommonsMenuItem-Controller","number":53,"title":"Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-f24/team01-f24-15/pull/53"}]
